spring:
  datasource:
    url: jdbc:mysql://localhost:3306/workshop_manager
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never